### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/sipgate#1]
- [x] Code Review
- [x] Add @simonkub as repo admin
- [x] Add to website
- [x] Create packagist package
- [x] Travis
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by simonkub** [comment]
hey @atymic, i just pushed my code to #2

**Comment by atymic** [comment]
I've added you as an admin & invited you to the github org.
CI also setup.

**Comment by atymic** [comment]
Website PR is here:
https://github.com/laravel-notification-channels/website/pull/3

Once you have merged i'll link packagist & merge the website PR

**Comment by simonkub** [comment]
- everything is pushed to master
- readme should be up to date with new badges and package name
- composer.json is up to date with new namespaces and package name
- marked my old package as deprecated

**Comment by atymic** [comment]
Live on packagist:
https://packagist.org/packages/laravel-notification-channels/sipgate

**Comment by atymic** [comment]
And website PR merged: https://github.com/laravel-notification-channels/website/pull/3

**Comment by atymic** [comment]
Should be good for you to tag the first release now :)

Thanks again

**Comment by simonkub** [comment]
Yep, release is tagged. Thank you too! :)
